### PR TITLE
Automatic file downloader!

### PR DESCRIPTION
**Pull request by oNyaaa1**
Automatic file downloader!
Fixed server not being shown in the server browser list, sv_region 255!

### CODE REVIEW

**Comment by Kefta** [comment]
False; http://facepunch.com/showthread.php?t=1374457&p=44566155&viewfull=1#post44566155

**Comment by oNyaaa1** [comment]
False; Valve > Facepunch https://developer.valvesoftware.com/wiki/Sv_region [Although hasn't been updated in donkeys years]

Although you maybe right!

His post: This isn't a guaranteed fix, however sv_region 255 seems to make some sort of a difference!

But the server still doesn't show on the steams legacy browser list, For me!

**Comment by Kefta** [comment]
sv_region was changed with TF2, and is now reflected in GMod. Meaning that page is outdated

**Comment by oNyaaa1** [comment]
Oh okay nice to know, I'll change to 0!

**Pull request merged**
