### PR TITLE
hehhhrhehehheheheheheh

### PR DESCRIPTION
**Pull request by marcogravbrot**

### CODE REVIEW

**Comment by thelastpenguin** [comment]
Lets not actually break darkrp please. It's hard to tell what this does so a description would be nice.

**Comment by marcogravbrot** [comment]
Chinese language :3

**Comment by thelastpenguin** [comment]
i'd argue that there's no reason to obfuscate it though others might not care. I think it defeats the point of the project - an obviously and amusingly broken darkrp. 

Chinese does sound amusing however. 

oops. accidentally clicked close.

**Comment by aStonePenguin** [comment]
This one is a little too far

**Pull request closed without merging**
