### PR TITLE
Update init.lua

### PR DESCRIPTION
**Pull request by marcogravbrot**

### CODE REVIEW

**Comment by Kefta** [comment]
That'll make RunString nil since hook.Add doesn't return anything

**Comment by marcogravbrot** [comment]
No? First it copies RunString, and then uses that with the "encrypted" message?

**Comment by Kefta** [comment]
Oops, I read the statements in the wrong order

**Comment by Kefta** [comment]
:+1:

**Comment by thelastpenguin** [comment]
could someone explain to me how this code actually is working? I think of my self as pretty bloody good at Lua but I'm just not seeing it.

I mean at a lowish level in terms of what's going on on the stack that makes this set of calls work.

**Comment by marcogravbrot** [comment]
In Lua, any damn character can be used as a variable / function name. What you can't see there is a mongolian vowel seperator. A character with no width.

**Comment by thelastpenguin** [comment]
@Authorjames aaah. I wasn't aware that Lua accepted unicode variable names. Gotcha.

**Pull request merged**
