### PR TITLE
Battering Ram fixes

### PR DESCRIPTION
**Pull request by Shigbeard**
The battering Ram was stupid so I fixed it

### CODE REVIEW

**Comment by Kefta** [comment]
I'm all for quality code, but unfortunately, this doesn't work at all

**Comment by Shigbeard** [comment]
All flacid memes aside, I was so fucking stoned when I wrote half that code. Still am smashed, so some pointers on what I dun goofed on... cheers

**Comment by Kefta** [comment]
You're using dot notation for functions instead of calling it from the metatable, you're calling IsPlayer on a trace and not an entity, you're resetting the LastGroup variable when you secondary fire, meaning it will change to SuperAdmin and not change back.

**Comment by Shigbeard** [comment]
I intended for it to not change back to superadmin, but ill patch that anyway.
I'll fix that trace bullshit.

And whats this about dot notations versus metatable?

**Comment by aStonePenguin** [comment]
doing tbl:Whatever(variable) will supply self as the first argument while tbl.Whatever(variable) will supply variable

**Comment by Shigbeard** [comment]
I still dont get it. The only thing I can think you guys are referring to is `self.LastGroup` which I've used the same way as the pre-existing `self.Ready`

**Comment by Shigbeard** [comment]
bump

**Comment by Kefta** [comment]
You're still not calling Kick correctly

**Comment by HDG-MrDeeJay** [comment]
Aww, do I really have to kick the other way?

**Comment by Shigbeard** [comment]
`Player:Kick( string reason="No reason given" )`
How am I doing that wrong? OR do you mean to kick using some other means (For instance using an admin mod of sorts)

**Comment by Shigbeard** [comment]
Omg...

It just dawned on me. Quick, I need 32x32 images of cardboard boxes!

**Comment by Shigbeard** [comment]
There. I'm now kicking properly.

Next problem in my bucket of rookie mistakes?

**Pull request merged**
