### PR TITLE
blowtorch

### PR DESCRIPTION
**Pull request by grimesx**
best weapon

### CODE REVIEW

**Comment by NotSoSuper** [comment]
:+1:

**Comment by bmwalters** [comment]
GitHub has reactions now, @NotSoSuper

**Comment by NotSoSuper** [comment]
like that @bmwalters

**Comment by NotSoSuper** [comment]
wow rude

**Comment by WilliamVenner** [comment]
wtf

**Comment by Kefta** [comment]
Fix'd

**Comment by WilliamVenner** [comment]
thx

**Comment by NotSoSuper** [comment]
LOL

**Pull request merged**
