### PR TITLE
Merged Sick State of the Art anticheat with TAC

### PR DESCRIPTION
**Pull request by Pengu1nZ**
Picked this up on scriptfodder for around 30 EUR, couldn't pass up a steal like this

### CODE REVIEW

**Comment by immibis** [comment]
This project is a parody, right?

**Comment by bmwalters** [comment]
no, are you implying our new RP gamemode is a joke? I'd like to see you do better.

**Comment by immibis** [comment]
Or is it just that file that's a joke? The new code is never executed anyway.

**Comment by bmwalters** [comment]
If you feel that you can program a hot new RP gamemode better than us, then just say so and make a PR.

**Pull request merged**
