### PR TITLE
More errors!

### PR DESCRIPTION
**Pull request by marcogravbrot**
Demonkush says there are not enough lua errors.

### CODE REVIEW

**Comment by oNyaaa1** [comment]
This is just stupid, Why would you want to error an gamemode, Come on get real dude, This is like your 3rd attempt now, And all you want to do is destroy the gamemode, If you really want to make an error gamemode why don't you?

**Comment by aStonePenguin** [comment]
I think he just wants it to be more like darkrp

**Comment by oNyaaa1** [comment]
DarkRP has errors since when, Just use DarkRP's error lol!

**Comment by Kefta** [comment]
Doesn't matter anyway since we overrided error with an empty function

**Pull request closed without merging**
