### PR TITLE
Update sv_chat.lua

### PR DESCRIPTION
**Pull request by AnonTakesOver**

### CODE REVIEW

**Comment by Kefta** [comment]
This will error since you're performing arithmetic on nil values

**Comment by AnonTakesOver** [comment]
I was under the assumption that string.find returned 0 if nothing was found.

**Comment by Kefta** [comment]
Nope, returns nil. Localise each one and put an or statement making it 0

**Comment by Kefta** [comment]
Also, string.find returns two values, so maybe you should just do a series of or nil checks

**Comment by AnonTakesOver** [comment]
if the starting position exists then the word exists in there.

**Comment by Kefta** [comment]
|| 0 > 0

9/11 quality checks

**Comment by AnonTakesOver** [comment]
:V
Wasnt sure if nil > 0 would error, so just in case.

**Pull request merged**
